### ISSUE TITLE
"You give up and reel in your line" message adding an additional line cast to the total.

### ISSUE THREAD

**Issue by DragonElite47** [samson-ffxi/HGather#3]
When fishing, the message "You give up and reel in your line.", seems to be adding 2 line casts instead of just 1 when the player cancels their cast.

This only occurs when using **bait**. Does not seem to occur when using a **lure**. 
This occurs when hooking and canceling monsters, but does not seem to occur when hooking and canceling items.
Does not seem to occur when canceling fish.

Screenshots with logs. I used /hgather clear before each test to ensure accurate reporting.

Hooking and canceling a monster adds an additional line cast. Seems to add to the lines cast count when you get the message that you caught something and also seems to add to the lines cast count when the "You give up and reel in your line." message appears.
So I believe that it is falsely reporting the "You give up and reel in your line." message as a line cast.
![Hgather mob cancel](https://github.com/user-attachments/assets/5a265193-ac7c-437e-92ab-3f33e11b3524)

However this does not occur when hooking and canceling an item.
![Hgather item cancel](https://github.com/user-attachments/assets/0b0bae9b-a2ef-405f-a75a-d73c13e3c41f)

**Comment by samson-ffxi** [comment]
Thanks for the report, I'll look into adding logic to avoid this.

**Comment by samson-ffxi** [comment]
Give the 1.7.1 version a try that I committed to the code repo, it probably fixes the count issue.
